export const FIND_CART_REQUEST ="FIND_CART_REQUEST";
export const FIND_CART_SUCCESS ="FIND_CART_SUCCESS";
export const FIND_CART_FAILURE ="FIND_CART_FAILURE";

export const  CLEARE_CART_REQUEST = "CLEARE_CART_REQUEST";
export const  CLEARE_CART_SUCCESS = "CLEARE_CART_SUCCESS";
export const  CLEARE_CART_FAILURE = "CLEARE_CART_FAILURE";

export const  GET_ALL_CART_ITEMS_REQUEST=" GET_ALL_CART_ITEMS_REQUEST";
export const  GET_ALL_CART_ITEMS_SUCCESS=" GET_ALL_CART_ITEMS_SUCCESS";
export const  GET_ALL_CART_ITEMS_FAILURE=" GET_ALL_CART_ITEMS_FAILURE";

export const ADD_ITEMS_TO_CART_REQUEST="ADD_ITEMS_TO_CART_REQUEST";
export const ADD_ITEMS_TO_CART_SUCCESS="ADD_ITEMS_TO_CART_SUCCESS";
export const ADD_ITEMS_TO_CART_FAILURE="ADD_ITEMS_TO_CART_FAILURE";

export const UPDATE_CARTIEM_REQUEST = " UPDATE_CARTIEM_REQUEST";
export const UPDATE_CARTIEM_SUCCESS = " UPDATE_CARTIEM_SUCCESS";
export const UPDATE_CARTIEM_FAILURE = " UPDATE_CARTIEM_FAILURE";

export const REMOVE_CARTITEM_REQUEST="REMOVE_CARTITEM_REQUEST";
export const REMOVE_CARTITEM_SUCCESS="REMOVE_CARTITEM_SUCCESS";
export const REMOVE_CARTITEM_FAILURE="REMOVE_CARTITEM_FAILURE";



